const RUN_MODE_UPDATE = 'RUN_MODE_UPDATE';
const INITIATE_LATENCY_CHECK = 'INITIATE_LATENCY_CHECK';
const STATE_UPDATE = 'STATE_UPDATE';
const IP_ADDRESS = 'IP_ADDRESS';
const START_INTERACTIVE_TOUR = 'START_INTERACTIVE_TOUR';
const REDUX_DISPATCH = 'REDUX_DISPATCH';

export const ipcChannels = {
  INITIATE_LATENCY_CHECK,
  IP_ADDRESS,
  REDUX_DISPATCH,
  RUN_MODE_UPDATE,
  START_INTERACTIVE_TOUR,
  STATE_UPDATE
};
