export enum AlertActionsTypes {
  ADD_ASYNC_ALERT = 'ADD_ASYNC_ALERT',
  REMOVE_ASYNC_ALERT = 'REMOVE_ASYNC_ALERT'
}

export enum ConsoleActionsTypes {
  UPDATE_CONSOLE = 'UPDATE_CONSOLE',
  CLEAR_CONSOLE = 'CLEAR_CONSOLE',
  TOGGLE_CONSOLE = 'TOGGLE_CONSOLE'
}